# Generated by Django 2.2.11 on 2020-03-26 17:34

from django.db import migrations, models
import djongo.models.fields
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('featureName', models.CharField(max_length=20)),
                ('currDimension', models.CharField(default=None, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wordContent', models.CharField(max_length=50)),
                ('rootWord', models.CharField(max_length=50)),
                ('dimensions', jsonfield.fields.JSONField()),
                ('language', djongo.models.fields.ArrayReferenceField(default=None, on_delete=djongo.models.fields.ArrayReferenceField._on_delete, to='wordDictionary.Language')),
            ],
        ),
        migrations.CreateModel(
            name='Dimension',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dimensionName', models.CharField(max_length=20)),
                ('features', djongo.models.fields.ArrayReferenceField(default=None, on_delete=djongo.models.fields.ArrayReferenceField._on_delete, to='wordDictionary.Feature')),
            ],
        ),
    ]
