# Generated by Django 2.2.11 on 2020-03-27 17:02

from django.db import migrations
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wordDictionary', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dimension',
            name='features',
        ),
        migrations.AddField(
            model_name='feature',
            name='dimension',
            field=djongo.models.fields.ArrayReferenceField(default=None, on_delete=djongo.models.fields.ArrayReferenceField._on_delete, to='wordDictionary.Dimension'),
        ),
    ]
