# Generated by Django 2.2.11 on 2020-03-27 17:48

from django.db import migrations
import djongo.models.fields
import wordDictionary.models


class Migration(migrations.Migration):

    dependencies = [
        ('wordDictionary', '0002_auto_20200327_1902'),
    ]

    operations = [
    ]
