# Generated by Django 2.2.11 on 2020-03-27 17:54

from django.db import migrations
import djongo.models.fields
import wordDictionary.models


class Migration(migrations.Migration):

    dependencies = [
        ('wordDictionary', '0003_auto_20200327_1948'),
    ]

    operations = [
    
    ]
