# Generated by Django 2.2.11 on 2020-03-27 18:04

from django.db import migrations
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wordDictionary', '0004_auto_20200327_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='dimension',
            field=djongo.models.fields.ArrayReferenceField(default=None, on_delete=djongo.models.fields.ArrayReferenceField._on_delete, to='wordDictionary.Dimension'),
        ),
        migrations.AlterField(
            model_name='word',
            name='language',
            field=djongo.models.fields.ArrayReferenceField(default=None, on_delete=djongo.models.fields.ArrayReferenceField._on_delete, to='wordDictionary.Language'),
        ),
    ]
