# Generated by Django 2.2.11 on 2020-03-31 10:31

from django.db import migrations, models
import djongo.models.fields
import wordDictionary.models


class Migration(migrations.Migration):

    dependencies = [
        ('wordDictionary', '0005_auto_20200327_2004'),
    ]

    operations = [
       
      
        migrations.RenameField(
            model_name='dimension',
            old_name='dimensionName',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='feature',
            old_name='featureName',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='word',
            old_name='wordContent',
            new_name='name',
        ),
        migrations.AddField(
            model_name='feature',
            name='dimension',
            field=djongo.models.fields.EmbeddedField(default=None, model_container=wordDictionary.models.Dimension, model_form_class=wordDictionary.models.DimensionForm, null=True),
        ),
        migrations.AddField(
            model_name='language',
            name='family',
            field=djongo.models.fields.EmbeddedField(default=None, model_container=wordDictionary.models.Family, model_form_class=wordDictionary.models.FamilyForm, null=True),
        ),
        migrations.AddField(
            model_name='word',
            name='language',
            field=djongo.models.fields.EmbeddedField(default=None, model_container=wordDictionary.models.Language, model_form_class=wordDictionary.models.LanguageForm, null=True),
        ),
        migrations.AddField(
            model_name='word',
            name='lemma',
            field=djongo.models.fields.EmbeddedField(default=None, model_container=wordDictionary.models.Lemma, model_form_class=wordDictionary.models.LemmaForm, null=True),
        ),
    ]
