# Generated by Django 2.2.11 on 2020-03-31 11:28

from django.db import migrations, models
import djongo.models.fields
import wordDictionary.models


class Migration(migrations.Migration):

    dependencies = [
        ('wordDictionary', '0007_auto_20200331_1331'),
    ]

    operations = [
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Lemma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('language', djongo.models.fields.EmbeddedField(default=None, model_container=wordDictionary.models.Language, model_form_class=wordDictionary.models.LanguageForm, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='feature',
            name='currDimension',
        ),
        migrations.RemoveField(
            model_name='word',
            name='rootWord',
        ),
    ]
