# Generated by Django 2.2.11 on 2020-03-31 16:16

from django.db import migrations, models
import djongo.models.fields
import wordDictionary.models


class Migration(migrations.Migration):

    dependencies = [
        ('wordDictionary', '0008_auto_20200331_1428'),
    ]

    operations = [
        migrations.CreateModel(
            name='POS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='word',
            name='dimensions',
        ),
        migrations.AddField(
            model_name='lemma',
            name='pos',
            field=djongo.models.fields.EmbeddedField(default=None, model_container=wordDictionary.models.POS, model_form_class=wordDictionary.models.POSForm, null=True),
        ),
        migrations.AddField(
            model_name='word',
            name='tagset',
            field=djongo.models.fields.EmbeddedField(default=None, model_container=wordDictionary.models.TagSet, null=True),
        ),
        migrations.CreateModel(
            name='TagSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('features', djongo.models.fields.ArrayReferenceField(default=None, on_delete=djongo.models.fields.ArrayReferenceField._on_delete, to='wordDictionary.Feature')),
            ],
        ),
    ]
