# Generated by Django 2.2.11 on 2020-03-31 17:10

import django.contrib.auth.models
from django.db import migrations, models
import django.utils.timezone
import djongo.models.fields
import wordDictionary.models


class Migration(migrations.Migration):

    dependencies = [
        ('wordDictionary', '0009_auto_20200331_1916'),
    ]

    operations = [
        migrations.AddField(
            model_name='lemma',
            name='author',
            field=djongo.models.fields.EmbeddedField(blank=True, model_container=django.contrib.auth.models.User, model_form_class=wordDictionary.models.UserForm, null=True),
        ),
        migrations.AddField(
            model_name='lemma',
            name='date_updated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='tagset',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='word',
            name='author',
            field=djongo.models.fields.EmbeddedField(blank=True, model_container=django.contrib.auth.models.User, model_form_class=wordDictionary.models.UserForm, null=True),
        ),
        migrations.AddField(
            model_name='word',
            name='date_updated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
