# Generated by Django 2.2.11 on 2020-03-31 18:01

from django.db import migrations, models
import djongo.models.fields
import wordDictionary.models


class Migration(migrations.Migration):

    dependencies = [
        ('wordDictionary', '0010_auto_20200331_2010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='author',
        ),
        migrations.AlterField(
            model_name='tagset',
            name='name',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.RemoveField(
            model_name='word',
            name='tagset',
        ),
    ]
