# Generated by Django 2.2.11 on 2020-03-31 18:03

from django.db import migrations
import djongo.models.fields
import wordDictionary.models


class Migration(migrations.Migration):

    dependencies = [
        ('wordDictionary', '0011_auto_20200331_2101'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='tagset',
            field=djongo.models.fields.EmbeddedField(default=None, model_container=wordDictionary.models.TagSet, model_form_class=wordDictionary.models.TagSetForm, null=True),
        ),
    ]
