# Generated by Django 2.2.11 on 2020-04-01 08:16

import django.contrib.auth.models
from django.db import migrations
import djongo.models.fields
import wordDictionary.models


class Migration(migrations.Migration):

    dependencies = [
        ('wordDictionary', '0012_word_tagset'),
    ]

    operations = [
        migrations.AddField(
            model_name='lemma',
            name='author',
            field=djongo.models.fields.EmbeddedField(blank=True, default=None, model_container=django.contrib.auth.models.User, model_form_class=wordDictionary.models.UserForm, null=True),
        ),
        migrations.AddField(
            model_name='lemma',
            name='language',
            field=djongo.models.fields.EmbeddedField(blank=True, default=None, model_container=wordDictionary.models.Language, model_form_class=wordDictionary.models.LanguageForm, null=True),
        ),
        migrations.AddField(
            model_name='lemma',
            name='pos',
            field=djongo.models.fields.EmbeddedField(blank=True, default=None, model_container=wordDictionary.models.POS, model_form_class=wordDictionary.models.POSForm, null=True),
        ),
    ]
