# Generated by Django 2.2.11 on 2020-04-01 08:47

import django.contrib.auth.models
from django.db import migrations
import djongo.models.fields
import wordDictionary.models


class Migration(migrations.Migration):

    dependencies = [
        ('wordDictionary', '0013_auto_20200401_1116'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='author',
            field=djongo.models.fields.EmbeddedField(blank=True, default=None, model_container=django.contrib.auth.models.User, model_form_class=wordDictionary.models.UserForm, null=True),
        ),
    ]
