# Generated by Django 2.2.13 on 2021-01-18 20:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_linguist',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='word',
            name='approved',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('proposedWord', models.CharField(default='', max_length=255)),
                ('note', models.TextField()),
                ('status', models.CharField(default='Pending', max_length=30)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='author', to=settings.AUTH_USER_MODEL)),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.Word')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seen', models.BooleanField(default=False)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('fromUser', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fromUser', to=settings.AUTH_USER_MODEL)),
                ('proposal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='api.Proposal')),
                ('toUser', models.ManyToManyField(related_name='toUser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
