# Generated by Django 2.2.13 on 2021-03-13 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210118_2048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='fromUser',
        ),
    ]
