PUT http://localhost:8000/api/accounts/changepassword/
Content-Type: application/json 
Authorization: token 2c178f01ec8bcee6f503c76148fa7618d026931c

{
    "old_password":"MPJYpsOrxNI",
    "new_password":"123456"
}